name: Publish Documentation

on:
  push:
    branches:
      - ci_cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
#      - name: Build and Publish Docs
#        run: |
#          ./gradlew dokkaHtml
#          git checkout --orphan gh-pages
#          git rm -rf .
#          cp -r ${{ github.workspace }}/build/dokkaHtml/* .
#          git add .
#          git commit -m "Publish documentation"
#          git push origin gh-pages --force
