name: Publish Documentation

on:
  push:
    branches:
      - ci_cd, main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
#
#      - name: Publish to Maven Local
#        run: ./gradlew publishToMavenLocal

      - name: Create documentation file
        run: ./gradlew dokkaHtml

      - name: Publish Docs
        run: |
          git config --global user.email "nikolayk@gini-apps.com"
          git config --global user.name "NikolayGini"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/NikolayGini/GiniLogger.git
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r ${{ github.workspace }}/gini_logger/build/dokka/html/* .
          git add .
          git commit -m "Publish documentation"
          git push origin gh-pages --force
